# Generated by Django 2.0.5 on 2018-06-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
